name: RegionControl
main: us.axefan.plugin.RegionControl
version: 0.2
author: axefan
database: true
description: Save and restore region contents and player inventory based on conditions and events.
commands:
    rc:
        description: Advanced region control.
        usage: /rc <action>